version: "3.8"
services:
  postgresdb:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: sql-exercise
    ports:
    - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
